//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kartowka.Packs.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PacksErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PacksErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kartowka.Packs.Core.Resources.PacksErrorMessages", typeof(PacksErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack data is invalid..
        /// </summary>
        public static string PackDataIsInvalid {
            get {
                return ResourceManager.GetString("PackDataIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack with the given ID was not found..
        /// </summary>
        public static string PackNotFound {
            get {
                return ResourceManager.GetString("PackNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions categories number per pack exceeded. Max number of categories allowed per pack is {0}..
        /// </summary>
        public static string PackQuestionsCategoriesLimitExceeded {
            get {
                return ResourceManager.GetString("PackQuestionsCategoriesLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions number per pack exceeded. Max number of questions allowed per pack is {0}..
        /// </summary>
        public static string PackQuestionsLimitExceeded {
            get {
                return ResourceManager.GetString("PackQuestionsLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packs number exceeded. Max number of packs allowed for a user is {0}..
        /// </summary>
        public static string PacksLimitExceeded {
            get {
                return ResourceManager.GetString("PacksLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question data is invalid..
        /// </summary>
        public static string QuestionDataIsInvalid {
            get {
                return ResourceManager.GetString("QuestionDataIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question with the given ID was not found..
        /// </summary>
        public static string QuestionNotFound {
            get {
                return ResourceManager.GetString("QuestionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions category data is invalid..
        /// </summary>
        public static string QuestionsCategoryDataIsInvalid {
            get {
                return ResourceManager.GetString("QuestionsCategoryDataIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions category with the given ID was not found..
        /// </summary>
        public static string QuestionsCategoryNotFound {
            get {
                return ResourceManager.GetString("QuestionsCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question type is unsupported..
        /// </summary>
        public static string QuestionTypeIsUnsupported {
            get {
                return ResourceManager.GetString("QuestionTypeIsUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round data is invalid..
        /// </summary>
        public static string RoundDataIsInvalid {
            get {
                return ResourceManager.GetString("RoundDataIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round with the given ID was not found..
        /// </summary>
        public static string RoundNotFound {
            get {
                return ResourceManager.GetString("RoundNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the given ID was not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
